Unknown instructions for linux
oscourse-tsinghua/OS2018spring-projects-g05 pull request #10
Opened 2018-04-06 16:33 UTC by XemboLiu

close issue #3 ，按照#3中comment的方式编写了对应的功能
注1：用dos2unix或者 unix2dos 指令转完所有的文件之后，仅有上一个pr所增加的测例有问题。（注：这项测试已经进行过，参见unknown_instructions_for_linux_test branch）
注2：由于我自己Vivado未确定的bug（添加仿真文件会导致仿真报错），xpr文件未进行merge，故其实际上是回退两个版本的xpr文件。

2018-04-07 01:51 UTC, roastduck requested changes
不要把那些变化只限于换行符的文件提交上来

2018-04-07 03:52 UTC, XemboLiu commented
相关问题已经被修改好，我也更新了xpr文件
但这并不意味着我认为上次pr新增加测例的换行符是正确的

2018-04-07 07:35 UTC, roastduck requested changes

2018-04-07 07:35 UTC, roastduck commented on thinpad_top/thinpad_top.srcs/sources_1/ip/lattice_ram/lattice_ram.xml
> +<<<<<<< HEAD
这里有merge冲突没处理

2018-04-07 09:44 UTC, XemboLiu commented
changes done

2018-04-07 10:37 UTC, roastduck requested changes
你是不是少上传了ehb/jrhb和jump/jrhb的仿真source？此外，你应该将测例加进工程。如果像蔡子熙那样出于客观原因加不了的，应在PR中列出所有测例。

2018-04-07 11:59 UTC, XemboLiu commented
这两个是我修改测例测试vivado时产生的冗余文件，新增的测例应该是tlb/tlbinvf和ehb/ehb两个。

2018-04-07 12:09 UTC, roastduck requested changes
Please improve the tests

2018-04-07 12:09 UTC, roastduck commented on sim/source/tlb/tlbinvf
> +# If TLBINVF works fine, we will come here.
If TLBINVF doesn't work fine, we won't come here, but this test won't fail, because none of the assertion is violated.

2018-04-07 12:09 UTC, roastduck commented on sim/output/ehb/ehb/ehb_tb.vhd
> +    assert user_reg(6) = x"0000ffff" severity FAILURE;
The test fails here on my machine

2018-04-07 12:33 UTC, roastduck commented on sim/output/ehb/ehb/ehb_tb.vhd
> +    assert user_reg(6) = x"0000ffff" severity FAILURE;
You may need to set a longer simulation period.

2018-04-07 14:18 UTC, roastduck commented on sim/source/tlb/tlbinvf
> +# If TLBINVF works fine, we will come here.
我想错了。Assert不是语句，无论如何都会执行。

2018-04-07 14:43 UTC, roastduck requested changes

2018-04-07 14:43 UTC, roastduck commented on thinpad_top/thinpad_top.xpr
> +>>>>>>> d79a2df5bb0ba1a7fcf2f2270dd0b0fa0e0fd7ce
我很怀疑你会不会用git

2018-04-07 15:51 UTC, roastduck requested changes

2018-04-07 15:51 UTC, roastduck commented on src/ex.vhd
> +        isExMtc0_o: out std_logic
`isXXMtc0`系列信号是不是跟`cp0RegWe`系列信号重复了？如果是，删掉`isXXMtc0`系列信号

2018-04-07 15:51 UTC, roastduck commented on src/id.vhd
> +                            isIdMtc0_o <= YES;
HI/LO寄存器有数据旁路，为什么要标记Hazzard？

2018-04-07 15:51 UTC, roastduck commented on src/id.vhd
> +                            isIdMtc0_o <= YES;
这里也是

2018-04-08 01:14 UTC, roastduck approved these changes

2018-04-08 01:18 UTC, merged