ll, sc, deret, config, watchhi and watchlo
oscourse-tsinghua/OS2018spring-projects-g05 pull request #25
Opened 2018-05-17 04:43 UTC by XemboLiu

close #4 and close #12

2018-05-17 06:48 UTC, roastduck requested changes
thinpad_top.xpr中对cp0_config_const的路径设置不正确，打开项目时会报错

2018-05-17 06:49 UTC, roastduck commented
另外你可以介绍以下之前Vivado crash是什么原因吗？

2018-05-17 09:44 UTC, XemboLiu commented
我不是很确定具体的原因，只知道问题是发生在debugpoint这部分中

2018-05-17 15:32 UTC, roastduck commented on sim/source/debugpoint/debugpoint_deret
> +# Move to entry Hi
哪里Move to entry Hi了？

2018-05-17 16:08 UTC, roastduck commented on src/cp0_reg.vhd
> +              curArr(BAD_V_ADDR_REG) when (conv_integer(raddr_i) = BAD_V_ADDR_REG and cp0Sel_i = "000") else -- BADVADDR and config1 is the only two registers we care with sel = 1 --
`BADVADDR`为什么要判断select为0？CP0 Register 8好像只有select=0一种情况啊

2018-05-17 16:18 UTC, roastduck commented on src/cp0_reg.vhd
> +                    regArr(CAUSE_REG)(CAUSE_WP_BIT) <= '0';
为什么要先通过`debugPoint_o`告诉ctrl有debug异常，然后再通过`isWatchIssued_i`设置寄存器？这是出于优先级考虑吗？

2018-05-17 16:22 UTC, roastduck commented on src/cp0_reg.vhd
> +                    if ((regArr(WATCHLO_REG)(WatchLoVAddrBits) = currentInstAddr_i(WatchLoVAddrBits)) and regArr(WATCHLO_REG)(WATCHLO_I_BIT) = '1') then
这是不是意味着要到写回阶段时才判断debug异常？这样会造成产生异常的指令对寄存器的修改已经写入，这是预期行为吗？如果不是的话，应该在访存阶段判断异常，就像发出其他异常的流程一样。

2018-05-17 16:27 UTC, roastduck commented on src/packages/except_const.vhd
> +    -- Cause of eret and deret is not in standard. We do this because 16~17 is implementation-dependent
虽然这里的改动显然是正确的，但是我想问一下为什么要改成16进制？MIPS规范里也是使用十进制称呼CP0寄存器的啊

2018-05-17 16:40 UTC, roastduck commented on src/packages/inst_const.vhd
> +    subtype InstSaFuncWidth         is integer range  7 downto  0;
Sa段+Func段不是从10到0吗，原来的没错吧？而且这个常量好像在整个工程里都没用到过，为什么要改？

2018-05-20 06:41 UTC, roastduck commented on src/packages/except_const.vhd
> +    -- Cause of eret and deret is not in standard. We do this because 16~17 is implementation-dependent
ModelSim likes this.

2018-05-20 06:49 UTC, roastduck commented on src/packages/inst_const.vhd
> +    subtype InstSaFuncWidth         is integer range  7 downto  0;
To be consistent with `InstSaFuncIdx`

2018-05-22 10:33 UTC, roastduck approved these changes

2018-05-24 03:28 UTC, merged